/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Coupang' at '14. 7. 23 오후 4:32' with Gradle 1.12
 *
 * @author Coupang, @date 14. 7. 23 오후 4:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
